### ISSUE TITLE
Dependencies required for visualize functionality not included in setup.py

### ISSUE THREAD

**Issue by timesler** [XtractTech/xt-training#32]
There are dependencies required to run the visualize script that are not included as package dependencies in the setup.py

**Comment by timesler** [comment]
We potentially don't want to increase the package's dependency footprint massively, so if many more packages are required, we could handle it in a similar way to pandas, where it gives an informative message like this for dependencies that aren't required for the package's core operation:

```bash
>>> import pandas as pd
>>> pd.read_parquet('asdfad')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 316, in read_parquet
    impl = get_engine(engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 31, in get_engine
    raise ImportError(
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
```
